### ISSUE TITLE
Request: Publish this package to pub.dev so i can use it as dependents for the MSIX package

### ISSUE THREAD

**Issue by YehudaKremer** [skyeskie/msix_config_version_match#1]
Hello @skyeskie 

I really like this yaml-version adaption feature,
its will make the use of [msix](https://pub.dev/packages/msix ) more straightforward.

If you have the time, please add this to [pub.dev](https://pub.dev/) so i can add and use this in the msix package.

Thank you 👍

**Comment by skyeskie** [comment]
I ended up using web-based (Sharepoint integration) for that project instead of Windows, so I haven't been using it for awhile. I can look at setting it up for publishing to `pub.dev`

Alternatively, since you manage [YehudaKremer/msix](https://github.com/YehudaKremer/msix), would you prefer I rewrite it for a merge into there? It's not really applicable to other packages, (except maybe something like cider).

I could see that working a couple different ways:

A) Run when no version specified. At https://github.com/YehudaKremer/msix/blob/4843b085aad0a8b8d3b1799181f31e80528087f6/lib/src/configuration.dart#L71 make a fallback call to copy over from the pubspec version.

B) Add a different config key or special version (`0.0.0.0`) that indicates it should copy over from the main pubspec version.

C) Include it more or less as-is under `bin`

------

The main problem I see using it directly in the `msix` package is mapping the 4th version number. I have it modifying the pubspec, and it was used in CI for the project after using [cider](https://pub.dev/packages/cider/) to bump the version number. This let me keep a build number as the 4th, and ignore all the `-alpha`, etc tags. Whenever `x.y.z` matched, Without keeping that information around, it'll be hard to tell how to handle some of the semver progressions.

Example:
* 2.0.0-alpha
* 2.0.0-alpha.2
* 2.0.0-beta
* 2.0.0-rc.1
* 2.0.0-rc.2
* 2.0.0-ProbablyDone
* 2.0.0

If throwing out the `msix_version` field (and thus not keeping track of builds), there's not a good way to map pre-release info, since the [semver spec](https://semver.org/#spec-item-9) is very loose. Even the build part can have multiple alphanumeric parts. Doing a stateless mapping, probably the best would be to map the last to `2.0.0.10` and the rest to `2.0.0.0`. Or potentially a date-based mapping, though not sure how it'd react to say a version `2.1.0.202202171751`

**Comment by YehudaKremer** [comment]
Hello @skyeskie 

Deep research, very helpful.

I think the alternative (A) option is the best.

On the other hand, I now remember from about a year ago,
that the Microsoft Store won't let you upload msix updates with the same version number, even if the **revision** number (1.0.0.Revision) is different from the last version.

The main usage with this package is to publish to the store,
so I think there is no reason to put a big effort to mirror the revision number to the `msix_version`.

But we still should copy the major, minor, and patch numbers to the msix_version, as a fallback like you said in option A.
